name: Build 
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build
      uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
      with:
        ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
        password: "Qa124956" 
    