name: Build 
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug
        uses: mxschmitt/action-tmate@v3
      - name: tmate  
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
          ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          password: "Qa124956" 
    
